const dbHandler = require("./queries/queries");

const db = new dbHandler("http://localhost:3001");

const rec = {
  issue_text: "Gently speaking can be better",
  created_by: "Rick Cavendish",
};
const id = "0aixmfcgd0a1vb0xtmztk9hkg8jrmv9uic667li7p040xgvh";

db.deleteRecord("apitest", "cippalippa", (err, data) => console.log(err));
// db.updateRecord("apitest", id, rec, (err, data) => console.log("***>", data));
// db.createRecord("apitest", rec, (err, data) => console.log("*** =>", err));
// db.getAllRecords("apitest", (err, data) => console.log("*** =>", data));
//

// {
//   err: null,
//   res: <ref *1> Response {
//     _events: [Object: null prototype] {},
//     _eventsCount: 0,
//     _maxListeners: undefined,
//     res: IncomingMessage {
//       _readableState: [ReadableState],
//       _events: [Object: null prototype],
//       _eventsCount: 4,
//       _maxListeners: undefined,
//       socket: [Socket],
//       httpVersionMajor: 1,
//       httpVersionMinor: 1,
//       httpVersion: '1.1',
//       complete: true,
//       rawHeaders: [Array],
//       rawTrailers: [],
//       joinDuplicateHeaders: undefined,
//       aborted: false,
//       upgrade: false,
//       url: '',
//       method: null,
//       statusCode: 200,
//       statusMessage: 'OK',
//       client: [Socket],
//       _consuming: false,
//       _dumped: false,
//       req: [ClientRequest],
//       text: '{"error":{}}',
//       [Symbol(kCapture)]: false,
//       [Symbol(kHeaders)]: [Object],
//       [Symbol(kHeadersCount)]: 14,
//       [Symbol(kTrailers)]: null,
//       [Symbol(kTrailersCount)]: 0
//     },
//     request: Test {
//       _events: [Object: null prototype],
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       _agent: false,
//       _formData: null,
//       method: 'delete',
//       url: 'http://127.0.0.1:50905/api/issues/apitest',
//       _header: [Object],
//       header: [Object],
//       writable: true,
//       _redirects: 0,
//       _maxRedirects: 5,
//       cookies: '',
//       qs: {},
//       _query: [],
//       qsRaw: [],
//       _redirectList: [],
//       _streamRequest: false,
//       app: [Server],
//       _okCallback: [Function (anonymous)],
//       _data: [Object],
//       req: [ClientRequest],
//       protocol: 'http:',
//       host: '127.0.0.1:50905',
//       _endCalled: true,
//       _callback: [Function (anonymous)],
//       res: [IncomingMessage],
//       response: [Circular *1],
//       called: true,
//       [Symbol(kCapture)]: false
//     },
//     req: ClientRequest {
//       _events: [Object: null prototype],
//       _eventsCount: 3,
//       _maxListeners: undefined,
//       outputData: [],
//       outputSize: 0,
//       writable: true,
//       destroyed: false,
//       _last: true,
//       chunkedEncoding: false,
//       shouldKeepAlive: false,
//       maxRequestsOnConnectionReached: false,
//       _defaultKeepAlive: true,
//       useChunkedEncodingByDefault: false,
//       sendDate: false,
//       _removedConnection: false,
//       _removedContLen: false,
//       _removedTE: false,
//       strictContentLength: false,
//       _contentLength: 19,
//       _hasBody: true,
//       _trailer: '',
//       finished: true,
//       _headerSent: true,
//       _closed: false,
//       socket: [Socket],
//       _header: 'DELETE /api/issues/apitest HTTP/1.1\r\n' +
//         'Host: 127.0.0.1:50905\r\n' +
//         'Accept-Encoding: gzip, deflate\r\n' +
//         'User-Agent: node-superagent/3.8.3\r\n' +
//         'Content-Type: application/json\r\n' +
//         'Content-Length: 19\r\n' +
//         'Connection: close\r\n' +
//         '\r\n',
//       _keepAliveTimeout: 0,
//       _onPendingData: [Function: nop],
//       agent: [Agent],
//       socketPath: undefined,
//       method: 'DELETE',
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       joinDuplicateHeaders: undefined,
//       path: '/api/issues/apitest',
//       _ended: true,
//       res: [IncomingMessage],
//       aborted: false,
//       timeoutCb: null,
//       upgradeOrConnect: false,
//       parser: null,
//       maxHeadersCount: null,
//       reusedSocket: false,
//       host: '127.0.0.1',
//       protocol: 'http:',
//       [Symbol(kCapture)]: false,
//       [Symbol(kBytesWritten)]: 0,
//       [Symbol(kNeedDrain)]: false,
//       [Symbol(corked)]: 0,
//       [Symbol(kOutHeaders)]: [Object: null prototype],
//       [Symbol(errored)]: null,
//       [Symbol(kHighWaterMark)]: 16384,
//       [Symbol(kRejectNonStandardBodyWrites)]: false,
//       [Symbol(kUniqueHeaders)]: null
//     },
//     text: '{"error":{}}',
//     body: { error: {} },
//     files: undefined,
//     buffered: true,
//     headers: {
//       'x-powered-by': 'Express',
//       'access-control-allow-origin': '*',
//       'content-type': 'application/json; charset=utf-8',
//       'content-length': '12',
//       etag: 'W/"c-3Rk1bge0s6VuJbi+S2m2iU0UGdY"',
//       date: 'Mon, 14 Oct 2024 15:21:24 GMT',
//       connection: 'close'
//     },
//     header: {
//       'x-powered-by': 'Express',
//       'access-control-allow-origin': '*',
//       'content-type': 'application/json; charset=utf-8',
//       'content-length': '12',
//       etag: 'W/"c-3Rk1bge0s6VuJbi+S2m2iU0UGdY"',
//       date: 'Mon, 14 Oct 2024 15:21:24 GMT',
//       connection: 'close'
//     },
//     statusCode: 200,
//     status: 200,
//     statusType: 2,
//     info: false,
//     ok: true,
//     redirect: false,
//     clientError: false,
//     serverError: false,
//     error: false,
//     created: false,
//     accepted: false,
//     noContent: false,
//     badRequest: false,
//     unauthorized: false,
//     notAcceptable: false,
//     forbidden: false,
//     notFound: false,
//     unprocessableEntity: false,
//     type: 'application/json',
//     charset: 'utf-8',
//     links: {},
//     setEncoding: [Function: bound ],
//     redirects: [],
//     [Symbol(kCapture)]: false
//   }
// }
